trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*/package.json'

pool:
  vmImage: ubuntu-latest

stages:
- stage: PublishPackages
  jobs:
  - job: PublishPackages
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 18.x
      displayName: Install Node.js

    - task: UseNode@1
      inputs:
        version: 18.x
        checkLatest: true

    - task: npmAuthenticate@0
      inputs:
        workingFile: ./.npmrc
      displayName: Authenticate with npm

    - script: |
        npm install --include=optional
      displayName: Install monorepo dependencies

    # CORE

    - script: |
        cd ./packages/stencil-library
        npm install
        npm run build
      displayName: Build Core

    - script: |
        cd ./packages/stencil-library
        npm publish
      displayName: Publish Core

    # REACT

    - script: |
        cd ./packages/react-library
        npm install
        npm run build
      displayName: Build React

    - script: |
        cd ./packages/react-library
        npm publish
      displayName: Publish React

    # VUE

    - script: |
        cd ./packages/vue-library
        npm install
        npm run build
      displayName: Build Vue

    - script: |
        cd ./packages/vue-library
        npm publish
      displayName: Publish Vue